#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

npm run check-format || (
    echo '🔴 Prettier Failed. Run npm run format, add changes and try to commit again'
        false;
)

npm run check-lint || (
    echo '🔴 Eslint Check Failed. Make the required changes listed above, add changes and try to commit again.'
          false;

)

npm run build || 
(
    echo 'your build failed
          Next build failed : View the errors above to see why.'
          false;
)

echo '🟢 Project Build successfully'